auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: registry.cn-hangzhou.aliyuncs.com/post_iptv/prometheus-adapter
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: registry.cn-hangzhou.aliyuncs.com/post_iptv/kube-state-metrics
  k8s.gcr.io/metrics-server/metrics-server: registry.cn-hangzhou.aliyuncs.com/post_iptv
  k8s.gcr.io/ingress-nginx/controller: registry.cn-hangzhou.aliyuncs.com/post_iptv
  k8s.gcr.io/git-sync/git-sync: registry.cn-hangzhou.aliyuncs.com/post_iptv
  gcr.io/kaniko-project/executor:debug,latest: registry.cn-hangzhou.aliyuncs.com/post_iptv
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: registry.cn-hangzhou.aliyuncs.com/post_iptv
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: registry.cn-hangzhou.aliyuncs.com/post_iptv
