auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/kustomize/kustomize : registry.cn-hangzhou.aliyuncs.com/post_iptv/kustomize
  gcr.io/google-containers/prometheus-to-sd : registry.cn-hangzhou.aliyuncs.com/post_iptv/prometheus-to-sd
