auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/sig-storage/csi-attacher: registry.cn-hangzhou.aliyuncs.com/post_iptv
  k8s.gcr.io/sig-storage/csi-provisioner: registry.cn-hangzhou.aliyuncs.com/post_iptv
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: registry.cn-hangzhou.aliyuncs.com/post_iptv
  k8s.gcr.io/sig-storage/csi-resizer: registry.cn-hangzhou.aliyuncs.com/post_iptv
  k8s.gcr.io/sig-storage/csi-snapshotter: registry.cn-hangzhou.aliyuncs.com/post_iptv
  
  
  
