auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: registry.cn-hangzhou.aliyuncs.com/post_iptv/prometheus-adapter
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: registry.cn-hangzhou.aliyuncs.com/post_iptv/kube-state-metrics
